ConicBundle: ConicBundle::QPKKT_ProbStats Class Reference
ConicBundle::QPKKT_ProbStats Class Reference
Internal QP Solver for linearly constrained groundsets
Used for collecting statics in QPKKTSolverComparison: For each bundle subproblem there is a block QPKKT_ProbStats (this), which holds for each KKT system a block of QPKKT_KKTStats, which holds for each solver a block QPKKT_SolverStats.
#include <QPKKTSolverComparison.hxx>
Public Member Functions
QPKKT_ProbStats ()
constructor
~QPKKT_ProbStats ()
destructor
CH_Matrix_Classes::Integer cnt_mu_cols (CH_Matrix_Classes::Real lbmu, CH_Matrix_Classes::Real ubmu)
for collecting the statistics for an interval of barrier parameter values, this first determines the number of KKT systems stored with barrier parameter in this range
int get_mu_stats (CH_Matrix_Classes::Real lbmu, CH_Matrix_Classes::Real ubmu, CH_Matrix_Classes::Indexmatrix &dims, CH_Matrix_Classes::Matrix &mu, CH_Matrix_Classes::Matrix &prepsecs, CH_Matrix_Classes::Matrix &predsecs, CH_Matrix_Classes::Matrix &corrsecs, CH_Matrix_Classes::Indexmatrix &predcalls, CH_Matrix_Classes::Indexmatrix &corrcalls, CH_Matrix_Classes::Matrix &cond, CH_Matrix_Classes::Indexmatrix &pccols, CH_Matrix_Classes::Matrix &sysviol)
collects the statistics for an interval of barrier parameter values by appending a column for each KKT system (the rows then correspond the solvers)
int get_prob_stats (CH_Matrix_Classes::Indexmatrix &dims, CH_Matrix_Classes::Indexmatrix &iterations, CH_Matrix_Classes::Matrix &lastmu, CH_Matrix_Classes::Matrix &prepsecs, CH_Matrix_Classes::Matrix &predsecs, CH_Matrix_Classes::Matrix &corrsecs, CH_Matrix_Classes::Indexmatrix &predcalls, CH_Matrix_Classes::Indexmatrix &corrcalls)
collects the cummulative values for each quadratic (bundle) subproblem. For each problem a new column is appended; in dims the rows give the dimensions stored in QPKKT_ProbStats; iterations gives the number of KKT systems in each subproblem; lastmu gives the value of the barrier parameter used in the last KKT system of the subproblem; for the other parameters the rows correspond to the cummulative values for each solvers
Public Attributes
CH_Matrix_Classes::Integer Qdim
the order of the H block (the quadratic/proximal term)
CH_Matrix_Classes::Integer Vdim
the low-rank rank of the H matrix
CH_Matrix_Classes::Integer Arowdim
rowdim of the constraints
CH_Matrix_Classes::Integer Aeqdim
with this number of equations
CH_Matrix_Classes::Integer Bdim
number of vectors in the bundle
CH_Matrix_Classes::Integer Cdim
number of constraints in the model
std::vector< CH_Tools::Microseconds > inittime
time spent in initializing the solver for a subproblem
std::vector< QPKKT_KKTStats > kktdata
one entry per KKT system
Friends
std::ostream & operator<< (std::ostream &out, const QPKKT_ProbStats &p)
(file-)output
std::istream & operator>> (std::istream &in, QPKKT_ProbStats &p)
(file-)input
Detailed Description
Used for collecting statics in QPKKTSolverComparison: For each bundle subproblem there is a block QPKKT_ProbStats (this), which holds for each KKT system a block of QPKKT_KKTStats, which holds for each solver a block QPKKT_SolverStats.
Member Function Documentation
get_prob_stats()
int ConicBundle::QPKKT_ProbStats::get_prob_stats (CH_Matrix_Classes::Indexmatrix & dims, CH_Matrix_Classes::Indexmatrix & iterations, CH_Matrix_Classes::Matrix & lastmu, CH_Matrix_Classes::Matrix & prepsecs, CH_Matrix_Classes::Matrix & predsecs, CH_Matrix_Classes::Matrix & corrsecs, CH_Matrix_Classes::Indexmatrix & predcalls, CH_Matrix_Classes::Indexmatrix & corrcalls) inline
collects the cummulative values for each quadratic (bundle) subproblem. For each problem a new column is appended; in dims the rows give the dimensions stored in QPKKT_ProbStats; iterations gives the number of KKT systems in each subproblem; lastmu gives the value of the barrier parameter used in the last KKT system of the subproblem; for the other parameters the rows correspond to the cummulative values for each solvers
Parameters
dims per column/subproblem: order of H, lowrank of H, # rows of A, # equalities in A, # rows of B, # rows of C
iterations number of KKTsystem of each subproblem
lastmu value of the barrier parameter in the last KKT system of the subproblem
prepsecs cummulative time spent in setting up the subproblem and systems (one row per solver)
predsecs cummulative time spent in solving the predictors (one row per solver)
corrsecs cummulative time spent in solving the correctors (one row per solver)
predcalls cummulative number of matrix vector multiplications in the predictors (one row per solver)
corrcalls cummulative number of matrix vector multiplications in the correctors (one row per solver)
References CH_Matrix_Classes::Matrix::coldim(), CH_Matrix_Classes::Indexmatrix::coldim(), CH_Matrix_Classes::Matrix::concat_right(), CH_Matrix_Classes::Indexmatrix::concat_right(), CH_Matrix_Classes::Matrix::enlarge_right(), CH_Matrix_Classes::Indexmatrix::enlarge_right(), CH_Matrix_Classes::Indexmatrix::init(), ConicBundle::QPKKT_SolverStats::operator<<, ConicBundle::QPKKT_SolverStats::operator>>, CH_Matrix_Classes::Matrix::rowdim(), and CH_Matrix_Classes::Indexmatrix::rowdim().
The documentation for this class was generated from the following file:
QPKKTSolverComparison.hxx