ConicBundle: ConicBundle::CBout Class Reference
ConicBundle::CBout Class Reference
Basic Support for Output Levels
base class for uniform use of WARNINGS and ERRORS (at some point in time)
#include <CBout.hxx>
Public Member Functions
virtual void set_out (std::ostream *out=0, int print_level=1)
Specifies the output level (out==NULL: no output at all, out!=NULL and level=0: errors and warnings, level>0 increasingly detailed information)
virtual void set_cbout (const CBout *cb, int incr=-1)
Specifies the output level relative to the given CBout class.
void clear_cbout ()
reset to default settings (out=0,print_level=1)
CBout (const CBout *cb=0, int incr=-1)
calls set_cbout
CBout (std::ostream *outp, int pl=1)
initialize correspondingly
CBout (const CBout &cb, int incr=0)
copy constructor
virtual bool cb_out (int pl=-1) const
Returns true if out!=0 and (pl<print_level), pl<0 should be used for WARNINGS and ERRORS only, pl==0 for usual output.
std::ostream & get_out () const
If cb_out() returned true, this returns the output stream, but it will abort if called with out==0.
std::ostream * get_out_ptr () const
returns the pointer to the output stream
int get_print_level () const
returns the print_level
virtual int mfile_data (std::ostream &out) const
writes problem data to the given outstream
Private Attributes
std::ostream * out
not output at all if out==0, otherwise use this output stream
int print_level
nonnegative level of output, 0 should mean WARNINGS and ERRORS only, 1 should represent normal output, everything above is regarded as more and more detailed information for debugging purposes
Detailed Description
base class for uniform use of WARNINGS and ERRORS (at some point in time)
Member Function Documentation
set_cbout()
virtual void ConicBundle::CBout::set_cbout (const CBout * cb, int incr = -1) virtual
Specifies the output level relative to the given CBout class.
Parameters
[in] cb use the same outstream as cb but change the print level by incr
[in] incr increment the print_level of cb by this value
Reimplemented in ConicBundle::SumBlockModel, ConicBundle::PSCAffineModification, ConicBundle::BundleSolver, ConicBundle::QPSolver, ConicBundle::QPConeModelBlock, ConicBundle::PSCAffineFunction, ConicBundle::UnconstrainedGroundset, ConicBundle::LPGroundset, ConicBundle::SOCSupportFunction, ConicBundle::NNCBoxSupportFunction, ConicBundle::GroundsetModification, ConicBundle::NNCBoxSupportModification, ConicBundle::SOCSupportModification, ConicBundle::UQPSumModelBlock, and ConicBundle::ModificationTreeData.
Referenced by CBout(), ConicBundle::PSCAffineFunction::get_generating_primal(), ConicBundle::SOCSupportFunction::get_socdim(), ConicBundle::NNCBoxSupportFunction::get_upper_bounds(), ConicBundle::NNCModelParametersObject::init(), ConicBundle::SOCModelParametersObject::init(), ConicBundle::BoxModelParametersObject::init(), ConicBundle::PSCModelParametersObject::init(), ConicBundle::LPGroundset::LPGroundset(), ConicBundle::SOCSupportModification::set_cbout(), ConicBundle::NNCBoxSupportModification::set_cbout(), ConicBundle::GroundsetModification::set_cbout(), ConicBundle::LPGroundset::set_cbout(), ConicBundle::UnconstrainedGroundset::set_cbout(), ConicBundle::QPConeModelBlock::set_cbout(), ConicBundle::QPSolver::set_cbout(), ConicBundle::PSCAffineModification::set_cbout(), ConicBundle::NNCModel::set_out(), ConicBundle::BoxModel::set_out(), ConicBundle::SOCModel::set_out(), ConicBundle::PSCModel::set_out(), ConicBundle::AFTModel::set_out(), and ConicBundle::SumBlockModel::set_out().
set_out()
virtual void ConicBundle::CBout::set_out (std::ostream * out = 0, int print_level = 1) virtual
Specifies the output level (out==NULL: no output at all, out!=NULL and level=0: errors and warnings, level>0 increasingly detailed information)
Parameters
[in] out (std::ostream*) direct all output to (*out). If out==NULL, there will be no output at all.
[in] print_level (int) any value <=0 should result in WARNINGS and ERRORS only
Reimplemented in ConicBundle::MatrixCBSolver, ConicBundle::SumBlockModel, ConicBundle::PSCAffineModification, ConicBundle::BundleSolver, ConicBundle::SumModel, ConicBundle::AFTModel, ConicBundle::PSCAffineFunction, ConicBundle::PSCModel, ConicBundle::AFTModification, ConicBundle::SOCModel, ConicBundle::BoxModel, ConicBundle::NNCModel, ConicBundle::SOCSupportFunction, ConicBundle::NNCBoxSupportFunction, ConicBundle::GroundsetModification, ConicBundle::NNCBoxSupportModification, ConicBundle::SOCSupportModification, and ConicBundle::UQPSumModelBlock.
Referenced by CBout(), ConicBundle::PSCAffineFunction::get_generating_primal(), ConicBundle::SOCSupportFunction::get_socdim(), ConicBundle::NNCBoxSupportFunction::get_upper_bounds(), ConicBundle::BundleSolver::set_cbout(), ConicBundle::SOCSupportModification::set_out(), ConicBundle::NNCBoxSupportModification::set_out(), ConicBundle::GroundsetModification::set_out(), ConicBundle::AFTModification::set_out(), ConicBundle::BundleSolver::set_out(), ConicBundle::PSCAffineModification::set_out(), and ConicBundle::SumBlockModel::set_out().
The documentation for this class was generated from the following file:
CBout.hxx